# This file describes the network interfaces available on your system
# For more information, see netplan(5).
network:
  version: 2
  renderer: networkd
  ethernets:
    enp0s5:
      dhcp4: yes
      dhcp6: yes
enp0s9:
  dhcp4: no
  addresses: [192.168.203.1/24]
