---
- hosts: ssh-copy-id
  gather_facts: yes
  tasks:
  - name: install bind9
    apt:
        update_cache: yes
        cache_valid_time: 3600
        name: "bind9"
        state: present
    become: true
    become_user: root
    become_method: su

  - name: copy named.conf.options
    copy: src=/etc/bind/named.conf.options dest=/etc/bind/named.conf.options.bak remote_src=true
    become: true
    become_user: root
    become_method: su

  - name: add to named.conf.options -1
    lineinfile:
      state: present
      line: 'listen-on { 192.168.57.1; };'
      dest: '/etc/bind/named.conf.options'
    become: true
    become_user: root
    become_method: su

  - name: add to named.conf.options -2
    lineinfile:
      state: present
      line: 'allow-transfer { none; };'
      dest: '/etc/bind/named.conf.options'
    become: true
    become_user: root
    become_method: su

  - name: add to named.conf.options -3
    lineinfile:
      state: present
      line: 'forwarders {8.8.8.8;8.8.4.4;};'
      dest: '/etc/bind/named.conf.options'
    become: true
    become_user: root
    become_method: su

  - name:  copy db.cuc.edu.cn from db.local
    copy: src=/etc/bind/db.local dest=/etc/bind/db.cuc.edu.cn remote_src=true
    become: true
    become_user: root
    become_method: su

  - name: change db.cuc.edu.cn
    lineinfile:
      state: present
      regexp: '^@       IN      A       127.0.0.1'
      line: ''
      dest: '/etc/bind/db.cuc.edu.cn'
      backrefs: yes
    become: true
    become_user: root
    become_method: su

  - name: add to db.cuc.edu.cn -1
    lineinfile:
      state: present
      line: '        IN      NS      ns.cuc.edu.cn.'
      dest: '/etc/bind/db.cuc.edu.cn'
    become: true
    become_user: root
    become_method: su

  - name: add to db.cuc.edu.cn -2
    lineinfile:
      state: present
      line: 'ns      IN      A       192.168.57.1'
      dest: '/etc/bind/db.cuc.edu.cn'
    become: true
    become_user: root
    become_method: su
  
  - name: add to db.cuc.edu.cn -3
    lineinfile:
      state: present
      line: 'wp.sec.cuc.edu.cn.      IN      A       192.168.57.1'
      dest: '/etc/bind/db.cuc.edu.cn'
    become: true
    become_user: root
    become_method: su

  - name: add to db.cuc.edu.cn -4
    lineinfile:
      state: present
      line: 'dvwa.sec.cuc.edu.cn.    IN      CNAME   wp.sec.cuc.edu.cn.'
      dest: '/etc/bind/db.cuc.edu.cn'
    become: true
    become_user: root
    become_method: su