---
- hosts: ssh-copy-id
  gather_facts: yes
  tasks:
  - name: install NFS
    apt:
        update_cache: yes
        cache_valid_time: 3600
        name: "nfs-kernel-server"
        state: present
    become: true
    become_user: root
    become_method: su

  - name: Create share directory (readonly)
    file:
      path: /nfs/general_r
      state: directory
      mode: '0444'
    become: true
    become_user: root
    become_method: su

  - name: Create share directory (read&write)
    file:
      path: /nfs/general_rw
      state: directory
      mode: '0666'
    become: true
    become_user: root
    become_method: su

  - name: Create under share directory (readonly)
    file:
      path: /nfs/general_r/files
      state: directory
      mode: '0444'
    become: true
    become_user: root
    become_method: su

  - name: Create under share directory (readonly)
    file:
      path: /nfs/general_rw/files
      state: directory
      mode: '0666'
    become: true
    become_user: root
    become_method: su

  - name: copy exports 
    copy: 
      src: /etc/exports 
      dest: /etc/exports.bak
      remote_src: true
    become: true
    become_user: root
    become_method: su

  - name: add general_r to exports
    lineinfile:
      state: present
      line: '/nfs/general_r 10.211.55.6(ro,sync,no_subtree_check)'
      dest: '/etc/exports'
    become: true
    become_user: root
    become_method: su

  - name: add general_rw to exports
    lineinfile:
      state: present
      line: '/nfs/general_rw 10.211.55.6(ro,sync,no_subtree_check)'
      dest: '/etc/exports'
    become: true
    become_user: root
    become_method: su

  - name: restart nfs server
    service: 
      name: nfs-kernel-server
      state: restarted
    become: true
    become_user: root
    become_method: su